object Libs {
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val MATERIAL = "com.google.android.material:material"
    const val COMPOSE_MATERIAL = "com.google.android.material:compose-theme-adapter"
    const val JUNIT = "junit:junit"
    const val JUNIT_EXT = "androidx.test.ext:junit"
    const val ESPRESSO = "androidx.test.espresso:espresso-core"
    const val COMPOSE_TEST = "androidx.compose.ui:ui-test-junit4"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val RECYCLER_VIEW = "androidx.recyclerview:recyclerview"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_COMPILER = "com.google.dagger:hilt-compiler"
    const val HILT_ANDROID_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val HILT_ANDROID_TESTING = "com.google.dagger:hilt-android-testing"

    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx"

    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_RUNTIME = "androidx.room:room-runtime"

    const val LIFECYCLE_LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIFECYCLE_RUNTIME_KTX = "androidx.lifecycle:lifecycle-runtime-ktx"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"

    const val HANDLE_BARS = "com.github.jknack:handlebars"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val CONVERTER_GSON = "com.squareup.retrofit2:converter-gson"
    const val WORK_RUNTIME = "androidx.work:work-runtime-ktx"
    const val HILT_WORK = "androidx.hilt:hilt-work"
    const val ANDROIDX_HILT_COMPILER = "androidx.hilt:hilt-compiler"
    const val CORE_TESTING = "androidx.arch.core:core-testing"
    const val MOCKK = "io.mockk:mockk"
    const val COROUTINE_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test"
    const val TEST_RUNNER = "androidx.test:runner"

    const val BENCHMARK = "androidx.benchmark:benchmark-junit4"
    const val BENCHMARK_MACRO = "androidx.benchmark:benchmark-macro"
    const val BENCHMARK_MACRO_JUNIT = "androidx.benchmark:benchmark-macro-junit4"
    const val PREFERENCE = "androidx.preference:preference-ktx"
    const val COMPOSE_UI = "androidx.compose.ui:ui"
    const val COMPOSE_ACTIVITY = "androidx.activity:activity-compose"
    const val COMPOSE_UI_TOOLKIT = "androidx.compose.ui:ui-tooling"
    const val COMPOSE_UI_MATERIAL = "androidx.compose.material:material"
}